version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
      - REDIS_URL=redis://redis:6379
      - CACHE_ENABLED=true
      - WEBSOCKET_ENABLED=true
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./front-end
    ports:
      - "3000:80"
    depends_on:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

volumes:
  mongo-data:
