import { ProfileModel } from "../data/ProfileModel";

const profileData: ProfileModel[] = [
    {
        id: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVv3z-qdrQcOLy1SDW3Y0abdEQsgHW_Bu23A&s",
        name: "Alice",
        age: 30,
        gender: "Female",
        location: {
            city: "New York",
            state: "NY",
            country: "United States",
            zip_code: "11004",
        },
        level: "Beginner",
        workout_preferences: ["Running", "Swimming"],
        bio: "Just somebody looking for a workout partner.",
    },
    {
        id: 2,
        image: "https://images.pexels.com/photos/39866/entrepreneur-startup-start-up-man-39866.jpeg",
        name: "John",
        age: 22,
        gender: "Male",
        location: {
            city: "Boston",
            state: "MA",
            country: "United States",
            zip_code: "02108",
        },
        level: "Advanced",
        workout_preferences: ["Running", "Cycling"],
        bio: "I like running and biking!",
    },
    {
        id: 3,
        image: "https://freerangestock.com/sample/152938/a-group-of-people-with-backpacks.jpg",
        name: "Bob",
        age: 32,
        gender: "Male",
        location: {
            city: "Boston",
            state: "MA",
            country: "United States",
            zip_code: "02109",
        },
        level: "Beginner",
        workout_preferences: ["Hiking", "Swimming"],
        bio: "I'm a swimmer.",
    },
    {
        id: 4,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAYJuwFoYWYcTT6lgqunl9JdSzWQNU-j40CQ&s",
        name: "Jane",
        age: 26,
        gender: "Female",
        location: {
            city: "New York",
            state: "NY",
            country: "United States",
            zip_code: "11004",
        },
        level: "Advanced",
        workout_preferences: ["CrossFit", "Jogging"],
        bio: "I'm an athlete in NY.",
    },
    {
        id: 5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIDGbMRABFFP6z6hBQClQmMKA1QqjqhNYRw&s",
        name: "Michael",
        age: 30,
        gender: "Male",
        location: {
            city: "New York",
            state: "NY",
            country: "United States",
            zip_code: "11004",
        },
        level: "Beginner",
        workout_preferences: ["Walking"],
        bio: "I love to take walks around New York.",
    },
    {
        id: 6,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgBeOKmbfE8VBojClOCyg73bVh-1BWHQWlww&s",
        name: "Julie",
        age: 20,
        gender: "Female",
        location: {
            city: "Amherst",
            state: "MA",
            country: "United States",
            zip_code: "01002",
        },
        level: "Intermediate",
        workout_preferences: ["Running", "Swimming"],
        bio: "I like running and swimming",
    },
    {
        id: 7,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlY1Kd3aC7BqbPsYM0CO4Tm640xeRpmWvgtA&s",
        name: "Maria",
        age: 27,
        gender: "Female",
        location: {
            city: "Diepholz",
            state: "Lower Saxony",
            country: "Germany",
            zip_code: "49356",
        },
        level: "Intermediate",
        workout_preferences: ["Running", "Swimming", "Yoga"],
        bio: "I like all kinds of workouts!",
    },
    {
        id: 8,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTTL6dUdZpcG3qmC2xyI-taMHV4IelTZg03Q&s",
        name: "Felix",
        age: 30,
        gender: "Nonbinary",
        location: {
            city: "Dortmund",
            state: "North Rhine-Westphalia",
            country: "Germany",
            zip_code: "44139",
        },
        level: "Advanced",
        workout_preferences: ["Swimming", "Balance exercises"],
        bio: "Exercising outside is great.",
    },
    {
        id: 9,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh6Z7cpOOJPkUEtFrRRBSJymgkuoBBEk3dCQ&s",
        name: "Isabella",
        age: 28,
        gender: "Female",
        location: {
            city: "Santibáñez De Vidriales",
            state: "Zamora",
            country: "Spain",
            zip_code: "49610",
        },
        level: "Beginner",
        workout_preferences: ["Boxing", "Rock Climbing", "Yoga"],
        bio: "I'm trying out some new activities.",
    },
    {
        id: 10,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoebAuvQZ7XRQ18wUCghd9K_FYqBs0SkhEAg&s",
        name: "George",
        age: 32,
        gender: "Male",
        location: {
            city: "Bitou Local Municipality",
            state: "Western Cape",
            country: "South Africa",
            zip_code: "6600",
        },
        level: "Intermediate",
        workout_preferences: ["Boxing", "Rock Climbing", "Weightlifting", "Walking"],
        bio: "Just somebody looking for a workout partner.",
    },
    {
        id: 11,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZV1torLuc1utxlFsTi72_XAQo0tjz_wz2xw&s",
        name: "Jordan",
        age: 23,
        gender: "Nonbinary",
        location: {
            city: "Paris",
            state: "Paris",
            country: "France",
            zip_code: "75005",
        },
        level: "Beginner",
        workout_preferences: ["HIIT", "Dancing", "Hiking"],
        bio: "I love to dance.",
    },
    {
        id: 12,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiI-rIfvECAlLEkWHOGv-nLpfE4vIENfN2-Q&s",
        name: "Riley",
        age: 20,
        gender: "Nonbinary",
        location: {
            city: "Paris",
            state: "Texas",
            country: "United States",
            zip_code: "75461",
        },
        level: "Beginner",
        workout_preferences: ["CrossFit", "Swimming"],
        bio: "Working out is fun.",
    },
    {
        id: 13,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8e1RoMRZlL-VQZ2qFfgWleHRSVHsXaYsSVQ&s",
        name: "Aparna",
        age: 24,
        gender: "Female",
        location: {
            country: "Bangladesh",
            zip_code: "1000",
        },
        level: "Beginner",
        workout_preferences: ["Running", "Swimming"],
        bio: "Just somebody looking for a workout buddy.",
    },
    {
        id: 14,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnUGFOdiHVrD4ds6Sqg7w1aSWSK88HO6bsnA&s",
        name: "Alice",
        age: 30,
        gender: "Female",
        location: {
            state: "Alberta",
            country: "Canada",
            zip_code: "T0B 3L0",
        },
        level: "Intermediate",
        workout_preferences: ["Running", "Swimming"],
        bio: "The gym is nice.",
    },
    {
        id: 15,
        image: "https://placehold.co/150x150",
        name: "David",
        age: 30,
        gender: "Male",
        location: {
            country: "Guam",
            zip_code: "96910",
        },
        level: "Advanced",
        workout_preferences: ["Pilates", "Swimming", "Weightlifting"],
        bio: "Just somebody looking for a spotter.",
    }
];

export default profileData;
