const Countries = [
    "Andorra",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Bangladesh",
    "Belgium",
    "Bulgaria",
    "Brazil",
    "Canada",
    "Switzerland",
    "Czech Republic",
    "Germany",
    "Denmark",
    "Dominican Republic",
    "Spain",
    "Finland",
    "Faroe Islands",
    "France",
    "Great Britain",
    "French Guyana",
    "Guernsey",
    "Greenland",
    "Guadeloupe",
    "Guatemala",
    "Guam",
    "Guyana",
    "Croatia",
    "Hungary",
    "Isle of Man",
    "India",
    "Iceland",
    "Italy",
    "Jersey",
    "Japan",
    "Liechtenstein",
    "Sri Lanka",
    "Lithuania",
    "Luxembourg",
    "Monaco",
    "Moldavia",
    "Marshall Islands",
    "Macedonia",
    "Northern Mariana Islands",
    "Martinique",
    "Mexico",
    "Malaysia",
    "Holland",
    "Norway",
    "New Zealand",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Puerto Rico",
    "Portugal",
    "French Reunion",
    "Russia",
    "Sweden",
    "Slovenia",
    "Svalbard & Jan Mayen Islands",
    "Slovak Republic",
    "San Marino",
    "Thailand",
    "Turkey",
    "United States",
    "Vatican",
    "Virgin Islands",
    "Mayotte",
    "South Africa"
] as const;

export default Countries;
